services:
  portfolio-client:
    image: ${REGISTRY_USERNAME}/portfolio-client:latest
    build:
      context: nextjs-client
      dockerfile: Dockerfile
      args:
        PUBLIC_API_ENDPOINT: ${PUBLIC_API_ENDPOINT}
  portfolio-server:
    image: ${REGISTRY_USERNAME}/portfolio-server:latest
    build:
      context: rust-server
      dockerfile: Dockerfile
