on:
    push:
      branches:
        - main
    workflow_dispatch:
  
  jobs:
    build-image:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      env:
        PUBLIC_API_ENDPOINT: ${{secrets.API_BASE_URL}}
        REGISTRY_USERNAME: ghcr.io/${{ github.repository }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image
          run: | 
            docker compose build portfolio-client portfolio-server --no-cache
            docker compose push